### ISSUE TITLE
Notice: Undefined offset: 0 - lastfmapi/class/apibase.php (110)

### ISSUE THREAD

**Issue by alexanderahlsen** [matto1990/PHP-Last.fm-API#12]
I'm getting a constant error from using the libary at the moment. Could someone have a look at this? I can't find the error:

Notice: Undefined offset: 0 - lastfmapi/class/apibase.php (110);
Notice: Trying to get property of non-object - lastfmapi/class/apibase.php (111)

**Comment by matto1990** [comment]
This projects is currently not maintained - I've not done any PHP development in years. I've left it up here because I know a few people still use it.

If what you've found is a bug, I'd welcome a pull request with the fix. It is turns out to be a problem with the way you're using the library feel free to comment back with the solution for others to find.

Thanks!

**Comment by n7st** [comment]
I can't reproduce this on my local machine (PHP Version 5.5.19). Any further information on reproducing it? Do the sample programs work?

**Comment by samijnih** [comment]
I don't have this problem (PHP 5.6.10)

**Comment by devilcius** [comment]
_Undefined offset_ is caused by a last.fm random server error. The service is working normally now so it cannot be reproduced. At least, this patch prevents the api to break is such cases.
